---

version: "3.8"

services:

  web_server:
    build:
      context: ./web-server/
      args:
        buildno: 1
    container_name: web_server
    restart: always
    ports:
      - 80:80

  maria_db:
    image: mariadb
    container_name: maria_db
    restart: always
    volumes:
      - /var/lib/docker/volumes/maiadb/_data/:/var/lib/mysql
